# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

name: Java CI with Maven

on: #xảy ra sự kiện để kích hoặc việc build
  push: 
    branches: [ master ]  # Khi code được push bên branch master

jobs: # Những công việc sẽ được làm
  build:
    name: Build and Test
    runs-on: ubuntu-latest   # Đây là môi trường, có thể chạy trên container này luôn hoặc docker

    steps:
    - name: Build and Test
      uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven  # Chạy lệnh build and verify test unit
      run: mvn --batch-mode --update-snapshots verify
    - name: Copy file jar to artifact stage    
      run: mkdir staging && cp target/*.jar staging
    - name: Push to artifact stage repository 
      uses: actions/upload-artifact@v3
      with:
        name: Package
        path: staging
